#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

mount -a

#mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
#mount -t sysfs sysfs /sys
#mount -t proc none /proc

mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

for i in /etc/init.d/S?* ; do 
	# ignore dangling symlinks (if any) 
	[ ! -f "$i" ] && continue 

	case "$i" in 
	*.sh)  
	    # Source shell script for speed. 
	    ( 
	    trap - INT QUIT TSTP 
	    set start 
	    . $i 
	    ) 
	    ;; 
	*) 
	    # No sh extension, so fork subprocess. 
	    $i start 
	    ;; 
	esac 
done 
