#!/bin/sh

mount -a

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

for i in /etc/init.d/S?* ; do
	# ignore dangling symlinks (if any)
	[ ! -f "$i" ] && continue

	case "$i" in
	*.sh) 
	    # Source shell script for speed.
	    (
	    trap - INT QUIT TSTP
	    set start
	    . $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
	esac
done
