#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo "Mount Pseudo Filesystem ......"
mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t sysfs sysfs /sys
#echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
