CROSS_COMPILE		:= /home/vagrant/toolchain/bin/mips-openwrt-linux-
CFLAGS			+=
LDFLAGS			+=

AR			:= $(CROSS_COMPILE)ar 
AS			:= $(CROSS_COMPILE)as 
LD			:= $(CROSS_COMPILE)ld 
NM			:= $(CROSS_COMPILE)nm 
CC			:= $(CROSS_COMPILE)gcc
GCC			:= $(CROSS_COMPILE)gcc
CXX			:= $(CROSS_COMPILE)g++
CPP			:= $(CROSS_COMPILE)cpp 
RANLIB			:= $(CROSS_COMPILE)ranlib 
STRIP			:= $(CROSS_COMPILE)strip 
SSTRIP			:= $(CROSS_COMPILE)sstrip
OBJCOPY			:= $(CROSS_COMPILE)objcopy 
OBJDUMP			:= $(CROSS_COMPILE)objdump
GDB			:= $(CROSS_COMPILE)gdb

TOP_DIR			:= $(shell pwd)/../
KERNEL_DIR		:= $(TOP_DIR)/kernel/linux-4.1.23
BUILD_DIR		:= $(TOP_DIR)/build
HOST_TOOLS_DIR		:= $(TOP_DIR)/hostTools/bin
ROOTFS_DIR		:= $(TOP_DIR)/rootfs

IMAGE_NAME		:= som9331-squashfs-sysupgrade.bin
